export default [
  {
    id: "international",
    flag: "international",
    langNative: "English",
    langEnglish: "English",
    countryNative: "International",
    countryEnglish: "International",
    direction: "ltr",
  },
  {
    id: "ar-AE",
    flag: "ae",
    langNative: "\u0627\u0644\u0639\u0631\u0628\u064a\u0629",
    langEnglish: "Arabic",
    countryNative:
      "\u0627\u0644\u0625\u0645\u0627\u0631\u0627\u062a \u0627\u0644\u0639\u0631\u0628\u064a\u0629",
    countryEnglish: "United Arab Emirates",
    direction: "rtl",
  },
  {
    id: "es-AR",
    flag: "ar",
    langNative: "Espa\u00f1ol",
    langEnglish: "Spanish",
    countryNative: "Argentina",
    countryEnglish: "Argentina",
    direction: "ltr",
  },
  {
    id: "en-AU",
    flag: "au",
    langNative: "English",
    langEnglish: "English",
    countryNative: "Australia",
    countryEnglish: "Australia",
    direction: "ltr",
  },
  {
    id: "bs-BA",
    flag: "ba",
    langNative: "Bosanski",
    langEnglish: "Bosnian",
    countryNative: "Bosna i Hercegovina",
    countryEnglish: "Bosnia and Herzegovina",
    direction: "ltr",
  },
  {
    id: "bg-BG",
    flag: "bg",
    langNative: "\u0411\u044a\u043b\u0433\u0430\u0440\u0441\u043a\u0438",
    langEnglish: "Bulgarian",
    countryNative: "\u0411\u044a\u043b\u0433\u0430\u0440\u0438\u044f",
    countryEnglish: "Bulgaria",
    direction: "ltr",
  },
  {
    id: "pt-BR",
    flag: "br",
    langNative: "Portugu\u00eas",
    langEnglish: "Portuguese",
    countryNative: "Brasil",
    countryEnglish: "Brazil",
    direction: "ltr",
  },
  {
    id: "zh-CN",
    flag: "china",
    langNative: "\u4e2d\u6587",
    langEnglish: "Chinese",
    countryNative: "\u4e2d\u56fd",
    countryEnglish: "China",
    direction: "ltr",
  },
  {
    id: "es-CL",
    flag: "cl",
    langNative: "Espa\u00f1ol",
    langEnglish: "Spanish",
    countryNative: "Chile",
    countryEnglish: "Chile",
    direction: "ltr",
  },
  {
    id: "cs-CZ",
    flag: "cz",
    langNative: "\u010ce\u0161tina",
    langEnglish: "Czech",
    countryNative: "\u010cesk\u00e1 republika",
    countryEnglish: "Czech Republic",
    direction: "ltr",
  },
  {
    id: "de-DE",
    flag: "de",
    langNative: "Deutsch",
    langEnglish: "German",
    countryNative: "Deutschland",
    countryEnglish: "Germany",
    direction: "ltr",
  },
  {
    id: "da-DK",
    flag: "dk",
    langNative: "Dansk",
    langEnglish: "Danish",
    countryNative: "Danmark",
    countryEnglish: "Denmark",
    direction: "ltr",
  },
  {
    id: "et-EE",
    flag: "ee",
    langNative: "Eesti",
    langEnglish: "Estonian",
    countryNative: "Eesti",
    countryEnglish: "Estonia",
    direction: "ltr",
  },
  {
    id: "ar-EG",
    flag: "eg",
    langNative: "\u0627\u0644\u0639\u0631\u0628\u064a\u0629",
    langEnglish: "Arabic",
    countryNative: "\u0645\u0635\u0631",
    countryEnglish: "Egypt",
    direction: "rtl",
  },
  {
    id: "es-ES",
    flag: "es",
    langNative: "Espa\u00f1ol",
    langEnglish: "Spanish",
    countryNative: "Espa\u00f1a",
    countryEnglish: "Spain",
    direction: "ltr",
  },
  {
    id: "fi-FI",
    flag: "fi",
    langNative: "Suomi",
    langEnglish: "Finnish",
    countryNative: "Suomi",
    countryEnglish: "Finland",
    direction: "ltr",
  },
  {
    id: "fr-FR",
    flag: "fr",
    langNative: "Fran\u00e7ais",
    langEnglish: "French",
    countryNative: "France",
    countryEnglish: "France",
    direction: "ltr",
  },
  {
    id: "fr-BE",
    flag: "be",
    langNative: "Fran\u00e7ais",
    langEnglish: "French",
    countryNative: "la Belgique",
    countryEnglish: "Belgium",
    direction: "ltr",
  },
  {
    id: "el-GR",
    flag: "gr",
    langNative: "\u0395\u03bb\u03bb\u03b7\u03bd\u03b9\u03ba\u03ac",
    langEnglish: "Greek",
    countryNative: "\u0395\u03bb\u03bb\u03ac\u03b4\u03b1",
    countryEnglish: "Greece",
    direction: "ltr",
  },
  {
    id: "zh-HK",
    flag: "hk",
    langNative: "\u4e2d\u6587",
    langEnglish: "Chinese",
    countryNative: "\u9999\u6e2f",
    countryEnglish: "Hong Kong",
    direction: "ltr",
  },
  {
    id: "hr-HR",
    flag: "hr",
    langNative: "Hrvatski",
    langEnglish: "Croatian",
    countryNative: "Hrvatska",
    countryEnglish: "Croatia",
    direction: "ltr",
  },
  {
    id: "hu-HU",
    flag: "hu",
    langNative: "Magyar",
    langEnglish: "Hungarian",
    countryNative: "Magyarorsz\u00e1g",
    countryEnglish: "Hungary",
    direction: "ltr",
  },
  {
    id: "id-ID",
    flag: "id",
    langNative: "Bahasa Indonesia",
    langEnglish: "Indonesian",
    countryNative: "Indonesia",
    countryEnglish: "Indonesia",
    direction: "ltr",
  },
  {
    id: "he-IL",
    flag: "il",
    langNative: "\u05e2\u05d1\u05e8\u05d9\u05ea",
    langEnglish: "Hebrew",
    countryNative: "\u05d9\u05e9\u05e8\u05d0\u05dc",
    countryEnglish: "Israel",
    direction: "rtl",
  },
  {
    id: "it-IT",
    flag: "it",
    langNative: "Italiano",
    langEnglish: "Italian",
    countryNative: "Italia",
    countryEnglish: "Italy",
    direction: "ltr",
  },
  {
    id: "ja-JP",
    flag: "jp",
    langNative: "\u65e5\u672c\u8a9e",
    langEnglish: "Japanese",
    countryNative: "\u65e5\u672c",
    countryEnglish: "Japan",
    direction: "ltr",
  },
  {
    id: "lt-LT",
    flag: "lt",
    langNative: "Lietuvi\u0173",
    langEnglish: "Lithuanian",
    countryNative: "Lietuva",
    countryEnglish: "Lithuania",
    direction: "ltr",
  },
  {
    id: "lv-LV",
    flag: "lv",
    langNative: "Latvie\u0161u",
    langEnglish: "Latvian",
    countryNative: "Latvija",
    countryEnglish: "Latvia",
    direction: "ltr",
  },
  {
    id: "es-MX",
    flag: "mx",
    langNative: "Espa\u00f1ol",
    langEnglish: "Spanish",
    countryNative: "M\u00e9xico",
    countryEnglish: "Mexico",
    direction: "ltr",
  },
  {
    id: "ms-MY",
    flag: "my",
    langNative: "Bahasa Melayu",
    langEnglish: "Malay",
    countryNative: "Malaysia",
    countryEnglish: "Malaysia",
    direction: "ltr",
  },
  {
    id: "nl-NL",
    flag: "nl",
    langNative: "Nederlands",
    langEnglish: "Dutch",
    countryNative: "Nederland",
    countryEnglish: "Netherlands",
    direction: "ltr",
  },
  {
    id: "nl-BE",
    flag: "be",
    langNative: "Nederlands",
    langEnglish: "Dutch",
    countryNative: "Belgi\u00eb",
    countryEnglish: "Belgium",
    direction: "ltr",
  },
  {
    id: "no-NO",
    flag: "no",
    langNative: "Norsk",
    langEnglish: "Norwegian",
    countryNative: "Norge",
    countryEnglish: "Norway",
    direction: "ltr",
  },
  {
    id: "en-NZ",
    flag: "nz",
    langNative: "English",
    langEnglish: "English",
    countryNative: "New Zealand",
    countryEnglish: "New Zealand",
    direction: "ltr",
  },
  {
    id: "pl-PL",
    flag: "pl",
    langNative: "Polski",
    langEnglish: "Polish",
    countryNative: "Polska",
    countryEnglish: "Poland",
    direction: "ltr",
  },
  {
    id: "pt-PT",
    flag: "pt",
    langNative: "Portugu\u00eas",
    langEnglish: "Portuguese",
    countryNative: "Portugal",
    countryEnglish: "Portugal",
    direction: "ltr",
  },
  {
    id: "ro-RO",
    flag: "ro",
    langNative: "Rom\u00e2n\u0103",
    langEnglish: "Romanian",
    countryNative: "Rom\u00e2nia",
    countryEnglish: "Romania",
    direction: "ltr",
  },
  {
    id: "sr-RS",
    flag: "rs",
    langNative: "\u0421\u0440\u043f\u0441\u043a\u0438",
    langEnglish: "Serbian",
    countryNative: "\u0421\u0440\u0431\u0438\u0458\u0430",
    countryEnglish: "Serbia",
    direction: "ltr",
  },
  {
    id: "ru-RU",
    flag: "ru",
    langNative: "\u0420\u0443\u0441\u0441\u043a\u0438\u0439",
    langEnglish: "Russian",
    countryNative: "\u0420\u043e\u0441\u0441\u0438\u044f",
    countryEnglish: "Russia",
    direction: "ltr",
  },
  {
    id: "ar-SA",
    flag: "sa",
    langNative: "\u0627\u0644\u0639\u0631\u0628\u064a\u0629",
    langEnglish: "Arabic",
    countryNative: "\u0627\u0644\u0633\u0639\u0648\u062f\u064a\u0629",
    countryEnglish: "Saudi Arabia",
    direction: "rtl",
  },
  {
    id: "sv-SE",
    flag: "se",
    langNative: "Svenska",
    langEnglish: "Swedish",
    countryNative: "Sverige",
    countryEnglish: "Sweden",
    direction: "ltr",
  },
  {
    id: "sl-SI",
    flag: "si",
    langNative: "Sloven\u0161\u010dina",
    langEnglish: "Slovenian",
    countryNative: "Slovenija",
    countryEnglish: "Slovenia",
    direction: "ltr",
  },
  {
    id: "sk-SK",
    flag: "sk",
    langNative: "Sloven\u010dina",
    langEnglish: "Slovak",
    countryNative: "Slovensk\u00e1 republika",
    countryEnglish: "Slovakia",
    direction: "ltr",
  },
  {
    id: "ar-SY",
    flag: "arabia",
    langNative: "\u0627\u0644\u0639\u0631\u0628\u064a\u0629",
    langEnglish: "Arabic",
    countryNative: "\u0639\u0627\u0644\u0645\u064a",
    countryEnglish: "International",
    direction: "rtl",
  },
  {
    id: "th-TH",
    flag: "th",
    langNative: "\u0e20\u0e32\u0e29\u0e32\u0e44\u0e17\u0e22",
    langEnglish: "Thai",
    countryNative: "\u0e1b\u0e23\u0e30\u0e40\u0e17\u0e28\u0e44\u0e17\u0e22",
    countryEnglish: "Thailand",
    direction: "ltr",
  },
  {
    id: "tr-TR",
    flag: "tr",
    langNative: "T\u00fcrk\u00e7e",
    langEnglish: "Turkish",
    countryNative: "T\u00fcrkiye",
    countryEnglish: "Turkey",
    direction: "ltr",
  },
  {
    id: "uk-UA",
    flag: "ua",
    langNative: "\u0423\u043a\u0440\u0430\u0457\u043d\u0441\u044c\u043a\u0430",
    langEnglish: "Ukrainian",
    countryNative: "\u0423\u043a\u0440\u0430\u0457\u043d\u0430",
    countryEnglish: "Ukraine",
    direction: "ltr",
  },
  {
    id: "zh-TW",
    flag: "tw",
    langNative: "\u4e2d\u6587",
    langEnglish: "Chinese (Traditional)",
    countryNative: "\u53f0\u7063",
    countryEnglish: "China",
    direction: "ltr",
  },
  {
    id: "en-GB",
    flag: "uk",
    langNative: "English",
    langEnglish: "English",
    countryNative: "United Kingdom",
    countryEnglish: "United Kingdom",
    direction: "ltr",
  },
  {
    id: "en-US",
    flag: "us",
    langNative: "English",
    langEnglish: "English",
    countryNative: "United States",
    countryEnglish: "United States",
    direction: "ltr",
  },
  {
    id: "vi-VN",
    flag: "vn",
    langNative: "Ti\u1ebfng Vi\u1ec7t",
    langEnglish: "Vietnamese",
    countryNative: "Vi\u1ec7t Nam",
    countryEnglish: "Vietnam",
    direction: "ltr",
  },
];
